# Generated by Django 3.1.3 on 2020-12-20 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0004_auto_20201214_1706"),
    ]

    operations = [
        migrations.AlterField(
            model_name="watchlist",
            name="listing",
            field=models.ManyToManyField(
                related_name="watchlist", to="auctions.Listing"
            ),
        ),
    ]
